name: Replica Set Tests

on: [push, pull_request]

jobs:
  single-node-replica-set-on-default-port:
    name: MongoDB RS on default port v${{ matrix.mongodb-version }} — Node.js v${{ matrix.node-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
        mongodb-version: ['4.0', '4.2', '4.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: mongodb-test-rs

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/replica-set.js
        env:
          CI: true
          MONGODB_REPLICA_SET: mongodb-test-rs

  single-node-replica-set-on-custom-port:
    name: MongoDB v${{ matrix.mongodb-version }} RS on custom port — Node.js v${{ matrix.node-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
        mongodb-port: [23456]
        mongodb-version: ['4.0', '4.2', '4.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-port: ${{ matrix.mongodb-port }}
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: mongodb-test-rs

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/replica-set.js
        env:
          CI: true
          MONGODB_PORT: ${{ matrix.mongodb-port }}
          MONGODB_REPLICA_SET: mongodb-test-rs


  single-node-replica-set-with-node-container:
    name: Container to Container connection using MongoDB v${{ matrix.mongodb-version }} RS — Node.js v${{ matrix.node-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.2']
        node-version: [14]

    container: node:14
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-port: ${{ matrix.mongodb-port }}
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: mongodb-test-rs
          docker-network: ${{ job.container.network }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/replica-set.js
        env:
          CI: true
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ matrix.mongodb-port }}
          MONGODB_REPLICA_SET: mongodb-test-rs

