name: Single Instance With Auth

on: [push, pull_request]

jobs:
  single-instance-with-auth:
    name: Mongo v${{ matrix.mongodb-version }} - Node v${{ matrix.node-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
        mongodb-version: ['4.4', '5.0', '6.0']
        mongodb-db: ['ci']
        mongodb-username: ['ci']
        mongodb-password: ['ci']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-db: ${{ matrix.mongodb-db }}
          mongodb-username: ${{ matrix.mongodb-username }}
          mongodb-password: ${{ matrix.mongodb-password }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/single-instance
        env:
          CI: true
          MONGODB_DB: ${{ matrix.mongodb-db }}
          MONGODB_USERNAME: ${{ matrix.mongodb-username }}
          MONGODB_PASSWORD: ${{ matrix.mongodb-password }}
